[package]
name = "printpdf"
version = "0.3.2"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for writing PDF files"

[dependencies]
lopdf = { version = "0.27", default-features = false }
rusttype = { version = "0.8.2", default-features = false, features = ["std"] }
time = { version = "0.2.1", default-features = false, features = ["std"] }
log = { version = "0.4.8", optional = true }
usvg = { version = "0.11.0", default-features = false }
svgtypes = "0.5.0"

[dependencies.image]
version = "0.23"
default-features = false
features = ["gif", "jpeg", "png", "pnm", "tiff", "bmp"]
optional = true

[features]
default = ["embedded_images"]
clippy = []
logging = ["log"]
embedded_images = ["image"]
ico = ["image/ico"]
tga = ["image/tga"]
hdr = ["image/hdr"]
jpeg_rayon = ["image/jpeg_rayon"]
dxt = ["image/dxt"]
dds = ["image/dds"]
webp = ["image/webp"]
less-optimization = []

[target.'cfg(all(target_arch="wasm32",target_os="unknown"))'.dependencies]
js-sys = "0.3.40"

[badges]
travis-ci = { repository = "fschutt/printpdf" }
appveyor = { repository = "fschutt/printpdf" }
